
services:
  blog-counter:
    build: .
    container_name: blog-counter
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - type: bind
        source: ./visitor-stats.json
        target: /app/visitor-stats.json
